name: contributing

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pandas
  - pip:
    - jupyter-book
    # 0.13.2 is broken currently
    # https://github.com/pydata/pydata-sphinx-theme/issues/1274
    - pydata-sphinx-theme<0.13.2